site_name: Roblox Requests
site_url: 'http://requests.paric.xyz/'
repo_name: 'jpatrickdill/roblox-requests'
repo_url: 'https://github.com/jpatrickdill/roblox-requests'
google_analytics: ['UA-167278179-1', 'paric.xyz']

theme:
  name: 'material'
  palette:
    primary: 'green'
    accent: 'green'

markdown_extensions:
  - toc
  - admonition
  - codehilite

plugins:
  - markdownextradata: {}

nav:
  - Home: index.md
  - Guide:
    - Installation: guide/installation.md
    - Quickstart: guide/quickstart.md
    - Advanced Usage: guide/advanced.md
  - API Reference: api-reference.md


extra:
  version: 0.2.1
